volumes:
  nginx-shared:
  etcd_data:

services:
  nginx:
    image: nginx:alpine
    hostname: nginx
    ports:
      - "8000:8000"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx-shared:/nginx
    depends_on:
      - web

  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      timeout: 5s
      retries: 3

  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    env_file:
      - .env
    working_dir: /app
    ports:
      - "8888:8888"
    volumes:
      - nginx-shared:/nginx
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    command: docker/web/run_web.sh

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    command:
      - --appendonly yes
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      timeout: 5s
      retries: 3

  etcd:
    image: bitnami/etcd:latest
    environment:
      - ETCD_ENABLE_V2=true
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
    volumes:
      - etcd_data:/bitnami/etcd
    ports:
      - "2379:2379"

  apisix:
    image: apache/apisix:latest
    depends_on:
      - etcd
    volumes:
      - ./docker/apisix/config.yaml:/usr/local/apisix/conf/config.yaml:ro
    ports:
      - "9180:9180/tcp"
      - "9080:9080/tcp"

  mail:
    image: rnwood/smtp4dev:latest
    ports:
      - "2525:25/tcp"
      - "2526:80/tcp"
