volumes:
  nginx-shared:

services:
  nginx:
    image: nginx:alpine
    hostname: nginx
    ports:
      - "8000:8000"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx-shared:/nginx
    depends_on:
      - web
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    env_file:
      - .env
    working_dir: /app
    ports:
      - "8888:8888"
    volumes:
      - nginx-shared:/nginx
    command: docker/web/run_web.sh
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    command:
      - --appendonly yes
