"""add_webhook

Revision ID: f7a9caf180e6
Revises: 74f355f61b76
Create Date: 2025-05-12 17:06:50.826710

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f7a9caf180e6"
down_revision: Union[str, None] = "74f355f61b76"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "webhook",
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("modified", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "description", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True
        ),
        sa.Column("external_webhook_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_webhook_id"),
    )
    op.create_index(op.f("ix_webhook_created"), "webhook", ["created"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_webhook_created"), table_name="webhook")
    op.drop_table("webhook")
    # ### end Alembic commands ###
